name: Release CD

on:
  release:
    types: [ released ]

jobs:
  publish:
    name: ğŸ“¡ Production publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”ƒ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ”§ Install dependencies
        run: npm install

      - name: ğŸ—ï¸ Build library
        run: npm run build

      - name: ğŸ“¡ Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
